### ISSUE TITLE
Cesium visualization issue with asset id: 16408

### ISSUE THREAD

**Issue by Wyckliffe** [AnalyticalGraphicsInc/cesium-ion-community#118]
I am trying to upload a gltf  v2 3D object but the Cesium isn't able to process the data. Note that this file has a KHR_technique_webgl extension.

**Comment by lilleyse** [comment]
Hi @Wyckliffe,

The model is using an outdated version of the [KHR_techniques_webgl](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_techniques_webgl) extension back when it was called `KHR_technique_webgl` instead of `KHR_techniques_webgl`. CesiumJS won't be able to load it. Do you have any other versions of the model, like glTF 1.0?

**Comment by lilleyse** [comment]
@Wyckliffe, I'm going to close this for now but feel free to reopen if you have any questions.
