### ISSUE TITLE
Tiling issue with asset id: 17120

### ISSUE THREAD

**Issue by finanshow** [AnalyticalGraphicsInc/cesium-ion-community#127]
I use CityEngine to export a KML file of fews of building models. When i upload the file in to Cesium On, it warning this problem:We're having trouble with your data. To help fix it, please open an issue in our Github repository.
By the way, I could import obj file correctly, but when I try to get feature demo like this, it warning:Uncaught TypeError: pickedFeature.getProperty is not a function!
'<tr><th>AD</th><td>' + pickedFeature.getProperty('AD') + '</td></tr>' +
 '<tr><th>test</th><td>' + pickedFeature.getProperty('DOITT_ID') + '</td></tr>' +
 '<tr><th>test</th><td>' + pickedFeature.getProperty('SOURCE_ID') + '</td></tr>' +

[GY_KML.zip](https://github.com/AnalyticalGraphicsInc/cesium-ion-community/files/2926110/GY_KML.zip)

**Comment by lilleyse** [comment]
Hi @finanshow,

This issue was recently fixed but hasn't been deployed yet. We'll let you know when it's ready.

**Comment by finanshow** [comment]
> Hi @finanshow,
> 
> This issue was recently fixed but hasn't been deployed yet. We'll let you know when it's ready.

Thank you lilleyse.
Btw, could you share experience on how to build a city model including hundreds of buildings which could be import into Cesium and select each build and make some interaction with them?
I only got a whole model with CityEngine and selected it by whole part of it.

**Comment by lilleyse** [comment]
@finanshow The fix was deployed. If you re-upload the asset it should convert correctly.

I think the way you're exporting from CityEngine is fine. Each building is being saved as a single feature which is good.

Once you have the asset converted check out some of the 3D Buildings examples we have:
[3D Tiles Feature Picking](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Tiles%20Feature%20Picking.html&label=3D%20Tiles)
[3D Tiles Styling](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Tiles%20Feature%20Styling.html&label=3D%20Tiles)
[3D Tiles Interactivity](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Tiles%20Interactivity.html&label=3D%20Tiles)

Those should help give you some ideas for interacting with buildings and seeing their metadata.
