### ISSUE TITLE
GML upload stuck in "Retrieving data for processing..."

### ISSUE THREAD

**Issue by pablocbre** [AnalyticalGraphicsInc/cesium-ion-community#136]
I tried to add a CityGML to my Ion assets and faced the following issue:

The file uploads fine, but when it gets to the "Retrieving data for processing..." step, it gets stuck at 5.00% and does not advance no matter how much time given.

I have uploaded similar CityGML without any problems.

ID is 18311.

**Comment by lilleyse** [comment]
Hi @pablocbre, we have a fix in the works for this. It should be deployed in the next release.

**Comment by pablocbre** [comment]
Hi Sean, thanks a lot for the update. Is the bug related to some specific feature of the CityGML? Just wondering if I could tweak it slightly so it works when I upload it.

**Comment by lilleyse** [comment]
@pablocbre, yes actually there were two problems here - the stalling issue was on our end and the fix is almost ready to be deployed. The second problem is with the CityGML file.

The last line in the file (line 8275415) has an invalid character `<0x1a>` which causes the XML parsing to fail. You should delete this line and then re-upload the asset. You can do that right now, no need to wait for the other fix to be deployed.

**Comment by pablocbre** [comment]
@lilleyse, great, thanks a lot for the update. I'll try to fix that and reupload the file.

**Comment by lilleyse** [comment]
@pablocbre the "Retrieving data for processing..." stall was fixed and deployed. It now reports the error message (which in this case was the invalid character `<0x1a>`).
