### ISSUE TITLE
Question: boundedBy tag in CityGML

### ISSUE THREAD

**Issue by pablocbre** [AnalyticalGraphicsInc/cesium-ion-community#138]
Hi, I would like to ask you a couple questions. When uploading a CityGML to ion to generate a 3D Tiles asset...

- Is the `<gml:boundedBy>` tag _required_?
- Is the `<gml:boundedBy>` tag _relevant_? What I mean is: if the boundaries defined here are not aligned with the actual content of the CityGML, will anything bad happen?

And finally... is there some place where this kind of things are documented so I can check for myself and not steal your time?

Thanks a lot

**Comment by shehzan10** [comment]
> * Is the `<gml:boundedBy>` tag _required_?

No, but it is strongly recommended to have it because of EPSG, which is required.

> * Is the `<gml:boundedBy>` tag _relevant_? What I mean is: if the boundaries defined here are not aligned with the actual content of the CityGML, will anything bad happen?

We recompute the lower/upper information in the `boundedBy`/`Envelope` tags from the geometry. So it does not need to actually match the content. However, the EPSG is the all important information in these tags.

> And finally... is there some place where this kind of things are documented so I can check for myself and not steal your time?

I would have pointed you to the spec, but that is cruel because the spec is extremely large and has many places where things like EPSG can be defined. So we're happy to answer any specific questions like the one you asked there.

**Comment by pablocbre** [comment]
Great, thanks for the details. It's good to know you guys are recalculating the boundaries: this way we can add and remove nodes from a CityGML without doing it ourselves 👍

And thanks for the willingness to help, makes a big difference. We can close this!
