### ISSUE TITLE
Reversed lat/lon in 3D Tiles

### ISSUE THREAD

**Issue by pablocbre** [AnalyticalGraphicsInc/cesium-ion-community#145]
- I have recently reuploaded a CityGML to my Ion account. The geometry has stayed the same, I only needed to update some GML attributes. The first (working) CityGML was uploaded on 19/03/19. The one that's not right today (08/04/19).

- I am using a function to fly to selected buildings such as the one presented [here](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=3D%20Tiles%20Interactivity.html&label=3D%20Tiles) in lines 105-130. Previously, it worked like a charm.

- After uploading the new CityGML, flights are going quite far away (Africa instead of Europe) instead of to the picked feature. As I suspected, for some reason, the properties lat and lon of the picked feature are being reversed. I checked by debugging lines:

```
function zoom(feature) {
    var longitude = Cesium.Math.toRadians(feature.getProperty('longitude'));
    var latitude = Cesium.Math.toRadians(feature.getProperty('latitude'));
    var height = feature.getProperty('height');
    ...
```
Not a single change has happened in this code from when it worked 

- I can confirm coordinates have stayed the same in both CityGML files. I have manually checked a few cases.

- I am using Cesium 1.52.

**Did the 3D Tiles process revert the coordinates?**

**Comment by shehzan10** [comment]
Hi @pablocbre. There have been no changes that would affect latitude/longitude in the tilers.

Will you be able to provide the data so that we can test it?

**Comment by pablocbre** [comment]
Hi @shehzan10 sure. How can I send it to you?

**Comment by shehzan10** [comment]
@pablocbre The asset IDs will suffice, both the old and new version will be useful.

**Comment by pablocbre** [comment]
@shehzan10 the working one is asset 18639. The apparently reversed one is 20340.

**Comment by shehzan10** [comment]
Hi @pablocbre. I retiled your data and it seems to be working correctly for both data.

I modified the New York sandcastle so that you can load your asset IDs (line 26) into it with your token (line 1) and run it.

[Sandcastle](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html#c=1Vhtb9s2EP4rXPbBcmvTXdsBg5MUcx1nMZrEXqJk65YhoCXaJiKRAknlpUP++46iKFGyvTXbpwUIZPHunnvh3fGoMVUsT/FUcBzTJckTPYoiqlQo7ihHh6jzeXZ1cRvOPk3Ob08mF5PO/g2/4fdEontGH6gEFk4f0NjCXBdrQScqXseCa8I4lZ1uJaUiyikIWWlcvAKRLVHwTfGCMxbdzYVimgl+mWeZkJrGXfTnDUfwFwmuREJxIlZBJ1wzhRZSPCgwJBZUIS40UlYI+UC4MOHZWGG1rBKxoOByptchVXq0AkOVDqmU8APs0zKnDVfPREwTIJR2SLZa63ECKkaRUTBEHcJBO9G007MsKYvjhDZ51iymHTCkgC6DdsdFdCdyjbUk0V1QKauDpoVIFsTEOhZRnlKu8YrqSULNz49P0zjolCyFm21ckmXJ00fGY8ZXqsbvOdxaUekC2KpAWbkfkqUQw3uqMInjwNvtU7KgyVgkCS3cC7qexSyhiurWRrexbJw8RPt4dxRa8aAMtvnLZTJ0bJCtF1SJXEYUL6VIRwqYIQqDVyZb+6PLy0nYnx71TcK+GnR7NUpKHlmap5eRpJRfZiSiEymFHKIfLM9z94aXXli7vwiRhiIo/elaLiz0msoHpmiwzHnhPAqoAarytJ2rlrrvtFSBWhMOSdIqI9+8e9jiE8sUlDZFBESVxSjlsQkAz3JtM60yK0jFfZEllWFG6ZISnUtabzGkaMWJs7JmnLVFbZaWQY+Ago6DEqHb8FdSWOPOR2OdU0hsjA7rSsLtAvKUOe7DQ6+oGprcamV0z/lUhRjRRNENuEyKjErNqGoCQmJyPa+IL8Y1adJENCt/AwM9oLdru8OnjOKL6U8n4e34dDr+9D/f6Y0+uGOri97YUFPqxmotHgBySSD0Xx3As+nR0enEj2BVq3+TPk69Me5rziPnd0RgWTHCG6F2crtDbnUFraBXaN2up8fXJVaSZGsWgTrXO73VoiuOHYgHt7+JtqamEgHHh8V2FWtxzB7BoLdd9Bp1UGqPfx/COzKKnt6ytyiu0mc0rMPU22TT9FEDi9W8hW6y4COckCspch4Dpzmjt/AtYewAaue799kjSgUXyiRGZwvnWkj2xQwpyQzaETMGlsE8aVHw6eQ43IJwb/pFtCl/3VjHH2dhODvbIh8zRRYJPXJzyBFTmvCIAtJ5ni6g3Oezy2k4vZ7cTs+Pp+fT8HMT5Nnf0ue6Nhr5/s/dbet4VUsMO06NyZiyiT6dk5SaOcGVKcwkc58U+EIJ5Su9Bu6GNLbLJd9SSBQYZgZ8b/bhcVDK7aPXr9lG0flQbeTf2R/724/iDoJMft0UhuQeFqtbfAl8zm633fUGAzS5J0kO/aRqtzFVkWSZCf6WuB7VVGS1luMFVvoJmFKqCfYgMC3x62a8397iHceNfxYkgq+YzmNa94wzotdQ4xckhpJUwTbnO5VYp9vYT6j5fwFWSjWxqha0VcZSyztEtfVlTxk3e6E/S3qUoHKiVxnec2pfoTf4+0Z+u37lWrm9LNAkYZkSLMZ+pwxF3We3GdU0O4IUkqQCtq+NSBAzpRfd2JBwueBbx3S0rhmK14YOsVza0dv+OIaj4MSizA3vBeErGpS4PQvnxeItftM0GW4lXEFlpvVOh25JYUqUPocjcX2VhfasOJZgWNA+5+ockezxPU7hosnMreRpLqA3BZWSXml1D/kIZRFZj5fJE0zkXiuAUtGMk7KenJzXbaGZQ1U4htYJ5UI+dL9abdrGe2ifXq/12CAIIHfsarE6BSaNdfzz1ejoYhROx7ezq9C7CTQr+SW7Js1qVeQuM/x6jBKSZkHJ3vcp8+nt7HoCd/tfZj20g+B2r05Ln/ELlSIU4YOYM2dZF/V3YTXL1xj0M/S0GtK8UclNoIo73SNTI75KaODVc1Fm7/AVnIO3n8GfAqa7WT//Dfk3QHb+eNhS6J24Lp8Dz4Be7WXPN6yFaUuiEVp4f1eYWmsISu3d7aW+6UkELW+nh79uLct3Xllew51eyKCyr65L+2wBeAo4XZmj6mvZa5WXMC8RWQkWud2WtxePctGVzl5v76A4OT9Yph9ZWnwAymUSYDzQNM2g6VM1WOTRHZyykVIO71v3acVrCotqxhwiuVqQ4P3bHnL/b/AP/sSVwcgL2zpEMGt6ywshYyr7EvY8Vz7xuaW26O+0od6Mr/2Hoh0PASiJN9X1tciG6PuGSkdaCK1F6lNB58HAxecgZveIxYc3e61vdDd7CHqFUkBZ5klyyb7Qm70PBwPgb4glokjkGUy+CXkyLOvvPpzaRYzxwQBeN6VKf4Hd2lRQnD4bA6BdFGdQZG6K5UVy6KCc0IcDZi6/SMMVD0RNhAWYbgYk8+5udrAUE036C8YLX9cUdt7sZ+urAygdlSIv1FR/SXiBrrkZxJGZ74zECzWaEe8Fun4DdqSFm6nayjajf1bc0/9T+M0VfpeJG58BQOUJ8LcNdM+/AA)

In this sandcastle, you can also use the "Print Metadata" and then right click on any building to print all its attributes. The longitude/latitude looked correct to me.

Let me know what you find using this sandcastle.

**Comment by pablocbre** [comment]
Hi @shehzan10. Thanks to that metadata feature I was able to track down the problem, which was completely on my side. I mistakenly introduced reversed lat and lon attributes in the GML which, apparently overrode the ones that the tiling process generates. Funny behaviour, I was not aware of it.

Thanks a lot for your help and sorry for the confusion!

**Comment by shehzan10** [comment]
Great to hear that!
