### ISSUE TITLE
Tiling issue with asset id: 20798

### ISSUE THREAD

**Issue by Dionnald** [AnalyticalGraphicsInc/cesium-ion-community#147]
Hi,

Good day. I had uploaded a Citygml file downloaded from https://www.opengeodata.nrw.de/produkte/geobasis/3d-gm/3d-gm_lod2/

An error sho
![CityGML](https://user-images.githubusercontent.com/32415068/56184646-6bde7480-604d-11e9-9abb-335e445563f2.JPG)
wn as attached.

**Comment by shehzan10** [comment]
Hi @Dionnald. The SRS used by the NRW dataset is unfortunately not one that is recognized by GDAL. I believe this is because the SRS is under the AdV format rather than EPSG or OGC and GDAL/Proj.4 don't support AdV.

Will you be able to use an EPSG based SRS? According to epsg.io, the closest EPSG is `EPSG:25832`.

We have an issue https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/35 that will in the future allow setting the SRS on the website, but for now the solution would be to replace the SRS in the source files.

**Comment by OmarShehata** [comment]
@Dionnald I'm closing this to keep discussion in the issue linked above for better handling of SRS in CityGML. Feel free to follow up or open a new issue if the proposed workaround does not work.
