### ISSUE TITLE
Tiling issue with asset id: 21194

### ISSUE THREAD

**Issue by karumbu97** [AnalyticalGraphicsInc/cesium-ion-community#148]
Error: Invalid File
File: R3CityGML_Sample.gml
Additional Information: CityGMLElementParser::endElement called on unbound GeometryElementParser object f

or element <bldg:lod1multisurface> at line 1732086, column 25

**Comment by karumbu97** [comment]
I got this issue when i am uploading citygml file to cesium. How to solve this issue?

**Comment by shehzan10** [comment]
Hi @karumbu97 

It looks like lines 1732083-1732088 are an empty tag.
```
<core:cityObjectMember>
<bldg:Building>
<bldg:lod1MultiSurface>
</bldg:lod1MultiSurface>
</bldg:Building>
</core:cityObjectMember>
```

The same also is present on lines 2813487-2813491

It looks like the parser doesn't like it and is throwing an error. I'm going to open an issue so that this is fixed and the parser will simply ignore these tags.

For now, you can edit the file to remove those lines.

However, there also seems to be another issue with the data. It looks like you are using EPSG:4326 as the source SRS, however the coordinates of the envelope and geometry do not look valid in 4326. Are you sure the CityGML data is projected in 4326?

**Comment by karumbu97** [comment]
Hi @shehzan10, 
 Thanks for your help. Yeah, CityGML is projected from UTM-44N. I think it's due to the empty geometry exists in the CityGML . I converted 3d shapefile to CityGML with the FME software. May be the error occurs there. 

 Is there any other way(Programmatically like in javascript, in C#) to convert 3d Shapefile to CityGML without using FME software?.

**Comment by shehzan10** [comment]
Hi @karumbu97 looks like UTM 44N is [EPSG:32644](https://epsg.io/32644), so the CityGML file should contain this.

Unfortunately, I don't have any personal experience of generating CityGML from Shapefiles. I believe FME is the right solution for this.

Do you think you can find the empty features in the shapefile and delete those? Maybe then the processing will work correctly? I believe that FME is going to use the EPSG from the shapefile for CityGML. Maybe that's why its setting it to EPSG:4326?

**Comment by karumbu97** [comment]
Hi @shehzan10 , Now the problem solved. There is no error  when uploading to cesium, because i buffer 1.5m around the each polygon feature in arcgis as per the need. So, the null geometries are filtered. 

![3d tiles](https://user-images.githubusercontent.com/49720617/56592233-e5ef9a00-6607-11e9-80ba-fff639ab6f20.png)

**Comment by shehzan10** [comment]
Glad that you were able to fix the problem. I'm going to keep this issue open for now so that we can fix the empty tags issue and then close this.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
