### ISSUE TITLE
Minor styling inconsistency in Model Inspector

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium-ion-community#15]
@hpinkos I'm pretty sure the glTF background used to be black, now it's white:

![image](https://user-images.githubusercontent.com/1495196/40494192-42c6b22c-5f42-11e8-93db-f12b0d990c17.png)

Background of other panels remain black.

**Comment by hpinkos** [comment]
@mramato I made a comment about this when we added syntax highlighting to the asset code snippet.  This happened because both use Prism for highlighting and it would be tricky to have two versions of the css.  We eventually need to re-theme the whole model inspector to match the rest of the site, we just haven't had a chance to yet.
