### ISSUE TITLE
Tiling Draco Compressed Models

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium-ion-community#160]
Cesium ion supports compressing models with Draco, and you can render them CesiumJS will decompress (see https://cesium.com/blog/2018/04/09/draco-compression/).

But it would be nice to also allow uploading models that are already Draco compressed. Is this a feature you'd like to see? If so, comment or 👍 this issue!

**Comment by emackey** [comment]
Could be a great option for models with tons of geometry.  But just a caveat here, Draco compression is lossy compression.  So just like JPG, if you compress it, decompress it, and then compress the decompressed data, you're double-dipping on the lossiness.  Probably not a big deal, but something to be aware of if you're thinking of using Draco in an intermediate step like this instead of for delivery.

**Comment by dkoffler** [comment]
It would just be nice to have the ability to load either compressed or non-compressed tiles into Ionic using API access from our data existing data pipeline.

Currently when I upload a draco compressed asset I get the following error:

![image](https://user-images.githubusercontent.com/321369/57034843-979d5500-6c1e-11e9-8adc-12d207995ce1.png)

**Comment by OmarShehata** [comment]
Requested again here: https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/205

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
