### ISSUE TITLE
Failed to tile model with multiple extensions

### ISSUE THREAD

**Issue by Ualas** [AnalyticalGraphicsInc/cesium-ion-community#169]
Dear,

Asset id: 23553. I'm trying to submit a KML that was exported from CityEngine to Cesium Ion and I`m having an issue with the tiling. Can somenone please help me with these questions?

1. Whats is the issue? And how can I solve?
2. For the next time, is there any log that I can check to solve this by my self?
3. What would be the best format to export a Cityengine object in order to have a georeferenced 3D tile in Cesium?

Thanks,
Ualas

**Comment by OmarShehata** [comment]
Looks like the problem here is that the model ends with `.obj.dae` which causes the tiling pipeline to incorrectly detect the format. If you rename the model to just end with `.dae` and change the name in the KML file as well, it should work. 

We are working to improve the error messages that are shown in the ion dashboard, so if it's a known error it'll be shown there. 

As for best export options, if it's a lot of buildings, I'd go with KML+COLLADA as you have now.

**Comment by OmarShehata** [comment]
We've just released a fix for this, you can see it in the changelog here: https://cesium.com/ion/changelog#2019-07-09

Feel free to follow up or open a new issue if you're still running into any trouble!
