### ISSUE TITLE
Failed to tile GML file (id 30242)

### ISSUE THREAD

**Issue by fethibch** [AnalyticalGraphicsInc/cesium-ion-community#181]
I uploaded a gml file of quebec and i want to create 3D tiles to create my own Cybercity, but it seems the data are wrong .

**Comment by OmarShehata** [comment]
It looks like the issue here is that this CityGML file does not have a `CityModel` element which Cesium ion expects.

Can you tell me what you used to export/create this CityGML file?

**Comment by fethibch** [comment]
i used quebec.gml file provided by quebec portal. In fact i want to
generate 3D building of 1Km near Laval University.


Le lun. 10 juin 2019 à 21:57, Omar Shehata <notifications@github.com> a
écrit :

**Comment by OmarShehata** [comment]
> i used quebec.gml file provided by quebec portal

Do you have a link to that I can see?

**Comment by fethibch** [comment]
https://www.nrcan.gc.ca/earth-sciences/geography/place-names/data/9245
here a link , i downloaded the gml file of quebec unzipped it and importet to cesium ion but got error
Ialso tried some other gml file witch are lighter in size and the same error came out

**Comment by OmarShehata** [comment]
Ok, it looks like the issue is that Cesium ion currently has support for CityGML files, but not GML files. I think we can leave this issue open to see if others would like to request support for this.

In the mean time, I see a KML/KMZ download option on the data portal. This should be a supported format by ion if it's a KML+COLLADA. If it's a small enough KML you could also add it directly to CesiumJS like [in this code example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=KML.html) - please try this and let me know if it works @fethibch .

**Comment by fethibch** [comment]
Hi omar, in fact it worked for me exporting collada files into cesium ion but the buildings seams to be floating in the space, so instead i used a geojson file containing polygon representing the buildings and then i add hight to each building so it will become in 3D in cesium. The problem is the 3D buildings are transparent and i couldn't add density or even color the sides.
Any idea?

**Comment by OmarShehata** [comment]
@fethibch glad to hear the tiling part worked! If the buildings are floating, there are several things you can do. You can either use the clamp to ground feature before tiling (you should see this after you drag and drop the files in ion but before you upload) or you can move the tileset itself using the Adjust Tileset button in the top right in the ion dashboard.

Let me know if those options work for you. Otherwise, if you can send me a Sandcastle (https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html) link to the transparent buildings I'd be happy to take a look.

**Comment by tfili** [comment]
Looks like this is straightened out. Regular GML files aren't supported.
