### ISSUE TITLE
KML file with no 3D models produces internal error

### ISSUE THREAD

**Issue by DragoneyeDrone** [AnalyticalGraphicsInc/cesium-ion-community#192]
Asset id: 34197

Trying your system & Tutorial however it doesnt seem to work with my own Tile set.  Is this by design, or have a made an error?

**Comment by OmarShehata** [comment]
@DragoneyeDrone the problem is that the uploaded file does not contain any 3D models. The kind of KML/COLLADA input that Cesium ion can currently accept is where you'd have a 3D city, where each building is a COLLADA model, and the KML file describes the location of each building. 

For this file you uploaded, you can actually render it directly in CesiumJS. You can drag and drop it in the Cesium Viewer as an example (open https://cesiumjs.org/Cesium/Build/Apps/CesiumViewer and then drag and drop your .kmz file). Here's a code example of how to programmatically load a KML/KMZ file: https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=KML.html

I'm keeping this issue open since this is an error that the interface should catch and inform the user.

**Comment by OmarShehata** [comment]
I also think it would be good to explain somewhere in our documentation/tutorial what kind of KML/COLLADA files are accepted. The [getting started tutorial](https://cesium.com/docs/tutorials/getting-started/#loading-your-own-data) actually has a KMZ file with a single building that is an example of the type of input Cesium ion expects.

**Comment by OmarShehata** [comment]
Cesium ion will now report if the KML/KMZ file does not contain any models! See change log here: https://cesium.com/ion/changelog#2019-07-26

In these cases, you can just add your data directly to your CesiumJS app as I describe above https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/192#issuecomment-511539818.
