### ISSUE TITLE
CityGML with .shp.xml file produces internal error

### ISSUE THREAD

**Issue by wukong-c** [AnalyticalGraphicsInc/cesium-ion-community#199]
Asset ID: 34679

**Comment by OmarShehata** [comment]
@cpgood the problem is that the uploaded zip contains files we don't support (like `.shp`). If you only include the CityGML files in your upload it should work. Let me know if you're having issues with that.

I'm leaving this issue open to improve our error reporting so we can catch and communicate that.

**Comment by mramato** [comment]
The specific issue here is not the `shp` file itself but the `DeliveryArea.shp.xml` file that is included along with it.  Since `xml` is a valid extension for CityGML files, it treats it as CityGML.

A potential solution here would be to skip invalid "CityGML" files and treat them as a warning instead.

**Comment by wukong-c** [comment]
It was so, thank you！

**Comment by susgut** [comment]
Concerning issue with asset it 72232, I have reviewed the zip file and id does not contain any .shp.xml file, so I am afraid that this is not the problem. Thank you anyway

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

If you have any follow up questions, please post on the community forum!
