### ISSUE TITLE
Usage statistics

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium-ion-community#20]
We want to add the ability for users to see how much data and how many Bing sessions they are using.  They should be able to view this information in aggregate and also for individual access tokens.

**Comment by mramato** [comment]
Our initial support for usage tracking went live a while ago at https://cesium.com/ion/usage

If anyone has feedback or additional feature requests pertaining to usage, just let us know.

**Comment by Tugark** [comment]
> Our initial support for usage tracking went live a while ago at https://cesium.com/ion/usage
> 
> If anyone has feedback or additional feature requests pertaining to usage, just let us know.

Is this working as intended as of today? I've been experimenting on our side with assets (Cesium World Terrain, own CityGML 3DTiles), both on the CesiumION sandcastle, localhost and server, and I still don't see any usage in my account.

Is there some sort of treshold, like with Google Maps where a certain amount of API calls per day/week/month is free? If so, I might have overread it in the docs, or it is missing from the docs :-) The feature itself would be very useful to us, in order to evaluate which account type we'd have to use for using Cesium ION in production.

I'd be glad to provide you with code examles, if needed.

**Comment by mramato** [comment]
@Tugark there can be a delay in your usage showing up depending on the overall number of requests our servers are receiving at any given time, but it should eventually "catch up".  If you are still not seeing your usage please let me know and we'll definitely dig further into it.  Thanks.

**Comment by hpinkos** [comment]
@Tugark if you're using an API token for your ion account, you should see usage start to populate the different tables on that page.  Make sure the first line of your CesiumJS applications is this:

```
Cesium.Ion.defaultAccessToken = '<paste your token here>';
```

You can find your token on this page: https://cesium.com/ion/tokens

As for whether you can make API calls for free, see details on our pricing page to see whether you qualify for a free community account or need to upgrade to a different plan: https://cesium.com/pricing/

**Comment by Tugark** [comment]
Hi there

@hpinkos @mramato We'll definitely need an API token for our usage, that I am sure of. But since no usage stats show up, I thought that maybe a certain amount of API calls are free. 

As such, I generated the token and use it in the following code (as Vue.js Component):

```javascript
<template>
    <div id="cesiumContainer"></div>
</template>

<script>
import Cesium from 'cesium/Cesium';
require('cesium/Widgets/widgets.css');

export default {
  name: 'BaseMapContainer',
  props: {
    msg: String
  },
  mounted: function() {
    Cesium.Ion.defaultAccessToken = '[MYTOKEN]';
    var viewer = new Cesium.Viewer('cesiumContainer', {
        fullscreenButton: false,
        timeline: false,
        sceneModePicker: false,
        navigationHelpButton: false,
        baseLayerPicker: false,
        animation: false,
        homeButton: false,
        geocoder: false,

        terrainProvider : new Cesium.CesiumTerrainProvider({
            url: Cesium.IonResource.fromAssetId(1)
        })
    });
    viewer.scene.globe.depthTestAgainstTerrain = true;

    var tileset = viewer.scene.primitives.add(
        new Cesium.Cesium3DTileset({
            url: Cesium.IonResource.fromAssetId(6762)
        })
    );

    viewer.zoomTo(tileset)
        .otherwise(function (error) {
            return error
        });
    }
}
</script>

<style scoped>
#cesiumContainer {
	width: 100%;
	height: 100%;
	margin: 0;
	padding: 0;
	overflow: hidden;
}
</style>
```
I also tested the token using a "wrong" token, which results in an error loading my asset.

**However,** my dashboard is still not populated. Furthermore, I can also not select any of my tokens from the list on top of that page - I can only use `Show usage for All`, the dropdown list itself is empty. (I just created a new token to check this, since my "main" token is the default one; I also tested it with both Chrome and Firefox and both show no results).

Please not that calls to my asset do not add to the statistics from both the Cesium ION sandcastle links as well as my own Vue.js test implementation. Also note that Cesium is only required in the BaseMapContainer.vue component, and only used in the above `mounted()` method.

**Comment by hpinkos** [comment]
Thanks for the extra info @Tugark!  We'll look into this and get back to you

**Comment by Tugark** [comment]
Just wanted to let you know that I now have the Token Selection available (Dropdown), but I don't see any usage statistics yet. At least during the time of these comments (beginning of October), there should be some usage, since I was experimenting with CesiumION then.

**Comment by hpinkos** [comment]
Thanks for the update @Tugark.  I've opened an issue for you here so we don't forget about it: #54

We haven't been able to reproduce this ourselves yet so I'm not quite sure what is going on.  We will follow up in #54 when we have more information.

**Comment by mramato** [comment]
@Tugark what is your ion user name?
