### ISSUE TITLE
Cesium visualization issue with asset id: 36648

### ISSUE THREAD

**Issue by chaitanyajalluri** [AnalyticalGraphicsInc/cesium-ion-community#206]
the dataset which is in format of .laz format is not able generate the tiles

**Comment by OmarShehata** [comment]
@chaitanyajalluri can you explain your issue a bit more? It looks like this dataset was tiled successfully. If you're having trouble visualizing it since it's an uncolored point cloud, you may need to set the attenuation and eye dome lighting, like in this Sandcastle example:

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html?src=3D%20Tiles%20Point%20Cloud%20Shading.html

**Comment by OmarShehata** [comment]
@chaitanyajalluri I'm closing this now, but feel free to follow up if you're still having trouble here.
