### ISSUE TITLE
Invalid or Unsupported CityGML tag is not caught

### ISSUE THREAD

**Issue by chaitanyajalluri** [AnalyticalGraphicsInc/cesium-ion-community#214]
Asset ID: 38202

Hi, I have uploaded the city gml data containing buildings into cesium ion, but it is not able to tile the city gml data.

**Comment by OmarShehata** [comment]
I think this CityGML file is invalid (according to at least this validator http://geovalidation.bk.tudelft.nl/schemacitygml/), although it's unclear exactly what the issue is. I'll update this issue as we investigate more. This also may just be an unsupported tag. You can see a list of the currently supported tags here:

https://cesium.com/docs/tutorials/uploading/

I think it would be good to have ion display a more meaningful error for this case.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
