### ISSUE TITLE
Support reading KML's ExtendedData when tiling models

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium-ion-community#222]
This came up [on the forum here](https://groups.google.com/d/msg/cesium-dev/JatWIqy_coE/V8FD30W9BAAJ). The only way to get an arbitrary number of metadata features right now with the online platform is using CityGML.

It is possible to specify per-model metadata in our pipeline with KML/COLLADA (example here https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/201#issuecomment-513325239). It would be nice to be able to do it with Cesium ion:

> My end goal is to be able to have a 3d map where some certain buildings are selectable and when clicking on them, some data is visualized that is not stored in the imported 3D model itself (ie it is referenced by eg building's material ID from another source). 

Maybe it would automatically read all the metadata, or show you a list of the fields that you can unselect etc.

**Comment by mramato** [comment]
Yesterday we went live with updates our tiling pipeline so that 3D Tiles produced from KML/COLLADA models now embed each Placemark's name and ExtendedData values into the tileset as per-feature data, which can then be accessed by CesiumJS, [3D Tiles styling](https://cesium.com/blog/2020/02/18/3d-tiles-styling-with-stories/) and [Feature picking](https://cesium.com/blog/2020/03/25/explore-data-with-picking/) (or really, anywhere the tileset is used).
