### ISSUE TITLE
Question regarding licensing

### ISSUE THREAD

**Issue by Son-HNguyen** [AnalyticalGraphicsInc/cesium-ion-community#23]
Dear Cesium team,

we are a university development team and have been using the open-source CesiumJS for our projects for quite some time. We've recently heard of Cesium ion and its licenses, which are not very clear to us at the moment. Thus, we have some questions regarding this matter:

1. Do we need a Cesium ion subscription or application key in order to host our current/existing projects using the open-source CesiumJS on our own server?

2. If we use the World Terrain Model and/or the Microsoft Bing Maps as Terrain Layer, do we need a Cesium ion subscription?

3. I suppose there is no need to acquire a Cesium ion subscription/token if we exclusively use our own data for the digital terrain model or use the OpenStreetMap base map?

Thank you for your help!

Best regards.

**Comment by hpinkos** [comment]
Hi @Son-HNguyen!

Starting September 1st, all users using Cesium World Terrain will need to create an ion account to get an access token in order to use that dataset in their CesiumJS applications.  You can read more about it in this blog post: https://cesium.com/blog/2018/03/01/introducing-cesium-world-terrain/

This token will also give you access to Bing Imagery served through ion.  If you're using Bing Maps Imagery and you already have an API key via https://www.bingmapsportal.com this will continue to work.

If you're using your own data hosted on your own server, you may not need a Cesium ion account.  However, Cesium ion does provide imagery/terrain processing and hosting services that may be useful for your tem.  We offer free plans for unfunded educational activities for which you may be eligible.  You can learn more at https://cesium.com/pricing/, or send an email to tim@cesium.com.

Hope this answers your questions!  I'm going to close this issue, but feel free to comment or create a new issue if you have more questions.
