### ISSUE TITLE
Failing to decode JPEG image inside glTF from Metashape

### ISSUE THREAD

**Issue by ferengi82** [AnalyticalGraphicsInc/cesium-ion-community#236]
Hi,
i tried too upload a *.glb file (3D-Mesh from Agisoft Metashape) and got an error. Asset ID 49550.

**Comment by OmarShehata** [comment]
Thanks for reporting this @ferengi82. Looks like this is a bug on our end with reading the JPEG images in this model. 

We'll take a look into fixing this. In the mean time, you can work around this issue by converting your `.glb` file to `.gltf` with separate JPEG images (you can do this with [gltf-pipeline](https://github.com/AnalyticalGraphicsInc/gltf-pipeline) using the `--separate` flag), and then re-exporting each image file with any image editing software like [Gimp](https://www.gimp.org/).

I would also recommend choosing `3D Capture` as an input type when tiling this on Cesium ion, since this is a photogrammetry model (captured from the real world). You'll get a more optimized 3D Tileset that way.

**Comment by ferengi82** [comment]
Hi,

i uploaded the convertet gltf and the re-exportet jpgs. now i get this error

```
We've encountered a problem with your data:

Error: File Not Found
File: 2019-10-11_Kelheim_Befreiungshalle.bin


If you'd like more help, open an issue in our Github repository or email support@cesium.com with the asset ID: 49723.
```

**Comment by OmarShehata** [comment]
That means you didn't upload all the the files needed by the converted glTF (the .bin file contains the geometry). You should see a `2019-10-11_Kelheim_Befreiungshalle.bin` in the same directory as the `.gltf`, so you should upload all those together.

**Comment by ferengi82** [comment]
thats embarrassing... thanks, now it worked!

**Comment by OmarShehata** [comment]
Glad to hear it! I'll keep this issue open so we can look into fixing the problem with the original JPEG images.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

I believe the original issue was resolved here, but if you have any follow up questions please post in the community forum!
