### ISSUE TITLE
Tiling issue with asset id: 50645

### ISSUE THREAD

**Issue by philadelphia76ai** [AnalyticalGraphicsInc/cesium-ion-community#237]
<Please provide a short summary of your data.>
Hello, I use FME to convert IFC file to CityGML and use Cesium ion to convert to 3D tiles, but Invalid file error happened.

Here is my cityGML file link [https://drive.google.com/file/d/1CN4i5qeWdlA__b-T9iCZtEczQSZAx08C/view?usp=sharing](url)

![upload err](https://user-images.githubusercontent.com/10768438/67552205-2bb72780-f73d-11e9-98b6-321fd37660af.PNG)

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

It looks like the issue here is that the CityGML file you uploaded is not valid. If you have any follow up questions, please post on the community forum!
