### ISSUE TITLE
Large model fails to convert to glTF

### ISSUE THREAD

**Issue by Cezary885** [AnalyticalGraphicsInc/cesium-ion-community#238]
Asset ID 52152.

I am trying to upload a 3D model from Pix4D Mapper in OBJ format (+mtl and jpg texture) but there seems to be some kind of tiling error just after the upload.
The model is small - one building and terrain around it

**Comment by Cezary885** [comment]
BTW the same model but from Reality Capture works well

**Comment by OmarShehata** [comment]
Thanks for reporting this @Cezary885 . I am able to successfully tile this model with the Cesium ion 3D tiling pipeline locally, so it may be an issue with resource consumption since tiling jobs on the online platform are run in a more constrained environment.

Can you share the asset ID of the model from Reality Capture that works?

**Comment by Cezary885** [comment]
Here is the ID: 51082

**Comment by OmarShehata** [comment]
@Cezary885 since this is a photogrammetry model, this should work and have better performance if you upload it with the option "3D Capture". Can you try that and let me know if it works for you?

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

If you have any follow up questions, please post on the community forum!
