### ISSUE TITLE
Large CAD with few materials fails to tile

### ISSUE THREAD

**Issue by russellar4** [AnalyticalGraphicsInc/cesium-ion-community#246]
Asset ID 55043. My .glb asset failed to import.  Assistance would be greatly appreciated.

**Comment by OmarShehata** [comment]
Hey @russellar4 , I responded to this over support email, but I'll include my response here as well:

This job failed because of an issue with our BIM/CAD tiler where it expects the model to contain many materials (it uses that as a hint to figure out what all the separate objects are, to create the ["level of detail based on visual importance" mentioned on this page](https://cesium.com/3d-tiling-pipeline/bim/)). 

This is something we want to improve support for, but in the meantime, as a workaround, would it be easy for you to re-export this using materials instead of vertex colors?

**Comment by russellar4** [comment]
I don't think it is using vertex colors, as I uploaded the OBJ (Asset
55774) that
I converted to glb using  https://github.com/AnalyticalGraphicsInc/obj2gltf,
and it also fails to import.

**Comment by OmarShehata** [comment]
@russellar4 thanks for the additional model. This OBJ is using materials, but it still has the same issue. There is one material that covers most of the geometry. The [Lumberyard Bistro](https://developer.nvidia.com/orca/amazon-lumberyard-bistro) model or the [San Miguel](https://sandcastle.cesium.com/index.html?src=3D%20Tiles%20Interior.html) model are good examples of the type of CAD data that's currently well supported.

We're going to look into improving support for this, I'll post in this issue when we have any updates.

**Comment by OmarShehata** [comment]
@russellar4 (I'm responding to your comment here to keep the discussion in the relevant issue)

> If it helps with troubleshooting. Asset 47481 is the same CAD model but imported from a fbx and it imported ok.
We can't use fbx for our application because our tool for reprojecting the models to ECEF can't output fbx only obj or glb.

I appreciate you sharing that. This definitely helps. The FBX file gets converted to glb as part of the tiling process, so the fact that this works is good news for getting the original glb version to tile. We'll investigate this more and I'll update this issue when we have an update.

**Comment by russellar4** [comment]
I exported a new model from Microstation with a lower Stroke Telerance: 0.01 meters and it imported successfully (asset 57853).

The original model that fails has a stroke tolerance of 0.001 m.

**Comment by ghost** [comment]
Omar wrote:
> This job failed because of an issue with our BIM/CAD tiler where it expects the model to contain many materials (it uses that as a hint to figure out what all the separate objects are, to create the ["level of detail based on visual importance" mentioned on this page](https://cesium.com/3d-tiling-pipeline/bim/)).

Hi, I'm curious if the lack of materials was the issue in the end or not. The output from a major BIM program like Navisworks typically has very few materials compared to the number of meshes. The ratio of materials to meshes can easily be on the order of 1:5000.

Thanks

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
