### ISSUE TITLE
Photogrammetry fails to tile

### ISSUE THREAD

**Issue by fidli** [AnalyticalGraphicsInc/cesium-ion-community#247]
Hello,

Are we hitting any limits with this dataset? Asset ID 56182.

I am trying to upload 2 GBs of gltf files (12 .gltf + 12 .bin) and the tiling fails.

When I take out one (any, it works, but my dataset is missing it, which i do not want)

Is there any list of limits except for the ones  here https://cesium.com/pricing/ ?

Am I doing something wrong? 

Thank you

**Comment by OmarShehata** [comment]
We spoke about this over support email, but just to update the issue here, this job is failing due to a bug on our end. There are no specific limits on file-size for 3D models other than the general 20 GB upload limit per-asset. 

A workaround for now is to split the model into more than 1 asset on Cesium ion and combine them into the one scene in your viewer.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
