### ISSUE TITLE
Tiling issue with asset id: 58893

### ISSUE THREAD

**Issue by navonyaniv** [AnalyticalGraphicsInc/cesium-ion-community#251]
Hello, OBJ format was successfully uploaded but is stuck on 9% for some time at the tiling progress. The file size is 1.2GB and is valid and loaded successfully on other software.
[Screenshot](http://dev.skylinesoft.com/Up/Navon/temp/obj.png).

**Comment by OmarShehata** [comment]
@navonyaniv this looks like a photogrammetry dataset. This is failing because it's being tiled as a CAD/BIM model. Can you try reuploading and selecting "3D Capture" in the drop down instead of "3D Model"?

That should fix it.

**Comment by navonyaniv** [comment]
@OmarShehata thank you. This is exactly what I already did and managed to cut into 3D-Tiles, however the textures are missing now. [screenshot](http://dev.skylinesoft.com/Up/Navon/temp/obj_no_textures.png).
I have removed the original asset and re-uploaded it as 60014

**Comment by OmarShehata** [comment]
@navonyaniv the produced 3D Tileset is missing textures before the model you files you uploaded didn't include any textures. I'd make sure to upload all files output from your photogrammetry software, including any JPEG/PNG images associated with this model.

**Comment by navonyaniv** [comment]
@OmarShehata Thanks again.
The *.obj has no textures indeed; this is a material linked model. You can see it when downloading the assed directly from my account. [Screenshot](http://dev.skylinesoft.com/Up/Navon/temp/obj_material.png).
Is it possible that the upload mechanism does not support *.obj matlib?

**Comment by OmarShehata** [comment]
@navonyaniv ah yes, I forgot to mention, for photogrammetry data Cesium ion will use the attached textures but will override the material definition, and use an [unlit material instead](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_unlit#khr_materials_unlit).

Is your goal to be able to control these material properties? Can you tell us a bit more about use case here (for example, is this mostly a metallic structure, and you need to be able to set the specular etc.? Or something else?) We can consider adding this as a feature to Cesium ion.

Note that since 3D Tiles uses glTF as the payload for the tiles, so the material definitions between OBJ and glTF won't exactly match (you can read more about [materials in glTF here](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#materials)).

**Comment by OmarShehata** [comment]
I'm closing this since the original issue was resolved, but if you have any more information you'd like to share about your use case with materials @navonyaniv that'd be great! And we can open a separate feature request on ways Cesium ion can support this.
