### ISSUE TITLE
b3dm-Model disappears when viewpoint is tilted

### ISSUE THREAD

**Issue by floka94** [AnalyticalGraphicsInc/cesium-ion-community#252]
![Issue](https://user-images.githubusercontent.com/29139420/70213141-f38e0600-1738-11ea-8ad1-1d0ffb6a83c5.gif)

I have created my own b3dm-Models and terrain-Data. When i tilt the viewpoint, then the b3dm-Model disappears at a specific viewpoint. 

I have already tried to get it work with the tips from the following issues:
- [https://github.com/AnalyticalGraphicsInc/cesium/issues/8095](url)
- [https://groups.google.com/forum/#!topic/cesium-dev/ypKGlP5ajZA](url)

Unfortunately, I have not managed yet to solve the problem.

**Comment by OmarShehata** [comment]
According to the forum thread you linked it, it looks like uploading the source data to Cesium ion and getting a 3D Tileset that way resolves the issue, is that right?

If so, it sounds like either the geometric error or the bounding volumes are not set up correctly in the tileset you created. You can visualize the bounding boxes using the 3D Tiles inspector in CesiumJS:

https://sandcastle.cesium.com/index.html?src=3D%20Tiles%20Inspector.html

**Comment by floka94** [comment]
I think you are right there is a problem with the bounding volumes and maybe with the transform.
If i use no terrain data, everything is working fine and i can see the bounding volume:
![pic3](https://user-images.githubusercontent.com/29139420/70248986-070e9080-177c-11ea-856e-8d1a24021178.PNG)

Buf if i use self generated terrain-data (.terrain) the bounding volumes are under the ground, and the .b3dm-Models disappear when i tilt the viewpoint:
![pic1](https://user-images.githubusercontent.com/29139420/70249073-29081300-177c-11ea-950f-4f3151595db7.PNG)

**Comment by OmarShehata** [comment]
@floka94 it's odd that the buildings aren't where the bounding volumes are (do you have some code that's pushing the individual tiles/models?) 

In any case, one thing you may find helpful here is that if you upload your custom terrain to Cesium ion, then upload your buildings, you can choose to clamp the buildings to the terrain to solve this problem. Let me know if that works for you. 

I'm going to close this issue for now since it isn't something we can take action on on our side, but feel free to follow up here or on the [Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev).
