### ISSUE TITLE
Oriented image planes in scene?

### ISSUE THREAD

**Issue by VePink** [AnalyticalGraphicsInc/cesium-ion-community#254]
Hello Cesium community. 
First of all I would like to thank you for developing such amazing product! I'm totally in love with it.
So far Cesium learning curve wasn't too steep, but now I'm finally stuck and must ask for help :)
I would like to add image planes to Cesium scene and be able to control following parameters:

- image position (lat, long, height); 

- image plane orientation (heading, pitch, roll); 

- image alpha;

- image source URL;

My testing results are here (Sandcastle link): https://bit.ly/2DWZPQB

Currently I have no luck with setting orientation and alpha. Also I would prefer using .jpeg images, but for some reason only .png's work.

I'm guessing I should use [Fabric](https://github.com/AnalyticalGraphicsInc/cesium/wiki/Fabric) materials. But I'm not sure if they work with ["plane" geometry type](https://cesium.com/docs/cesiumjs-ref-doc/PlaneGeometry.html). Also I'm not sure if "plane" geometry allows setting heading, pitch, roll parameters.

My goal is to create scene with real world images matched with camera positions (https://i.stack.imgur.com/UkvYr.gif) and elements of scene. Here is working example of something like this https://smapshot.heig-vd.ch/map/?imageId=95646 only with 3D navigation disabled.
Any feedback is welcome.

**Comment by OmarShehata** [comment]
Hey @VePink , thank you so much for the kind words! I absolutely appreciate your support and feedback here.

You shouldn't need to use Fabric for this unless you're trying to create some custom material. For setting the alpha, you just need to do this on the imageMaterial property. Here's a [modified Sandcastle example](https://sandcastle.cesium.com/#c=hVRrb9owFP0rV3whSJmdhFI2Sqt1bFOR9qi67qEpEnITN7Fw7Mh2qFjFf981aUuASXO+5D7O8bXPvV4xAyvBH7iBc1D8AWbciqYiP7a+oJ9tzZlWjgnFTX9wlqpUUXqZ5yAqVnCoJVOcpGqFTHPvWWw9C8etQ86WnHDlhBPcEpbnwWOq4GkpVvEJ9G943hL1w12s1hYxWk2ei5oxg6yCqSG5N7p6zwvDuQ2SEYniaDwehzAakZP4zethEkISkWjQZfP0E+js3fF2Tn7tPRAcbnlCvn+Z3y5+hXDA61cuKq4slmr3qF7ASTBMSBRCfHqMrZjjRjC5h9xe5OenyLXRNTduDcFB8X5tRcAbLJ2r7YTSppaa5eRBLLGmXDCiTUG9VXuLZrqqsEwa0YjRS7l2jSW1KvrhMXOmpTa7u/cW+Xk1v/2A5K68lHXJgoiMBvvITcfetL+btmnaFnmn9bJiZrmIsDkec2wSoZhXGf4nM+yIW8Xj02EIlMJcCWRgEhtGKAdSq0K4JvdN+QzwfZFE4yT6JwCNg/whigyolDvOLrkoSgfB7wEE1aCD0UZglx+c5YqzXKjiWrisvNFS7p1oh41P2spmOA6G4R5bVIf8VbyXUHu+ThjLTZ2v13+7NON33GXljWHtQMWwOesm3sv1SzSEwPpz+TH/iH6nX0SDCEVsB9pmHMc+28KJ5c4/GMFO3MFZL+xNrVtLftEW8FZUtTYOGiMDQqjjFc4e6kzvmmzJHcms9X0ypc+gaS5WIPLztHfwCKU9yCSzFiP3jZTfxB+e9i6mFPP3YH4Q8Ba/rriRbO1TyvjiU+skhEwpmscop7W8Y6bD+Bc) doing it.

For the image orientation, you should be able to set this either by changing the plane definition, or by setting the heading/pitch/roll, although there is a known issue with the latter: https://github.com/AnalyticalGraphicsInc/cesium/issues/8268

Let me know if this helps!  What kind of application are you building with Cesium?

**Comment by VePink** [comment]
Hey @OmarShehata , thank you for quick help. 

Setting alpha on .png works fine, but what about using .jpg/.jpeg? I would like to use this file format, because file sizes are smaller and I don't mind lossy compression.

I'm thinking about switching from PlaneGeometry to [FrustumGeometry](https://cesium.com/docs/cesiumjs-ref-doc/FrustumGeometry.html) if it is possible to apply different appearance on different faces of frustum geometry instance.

**Comment by OmarShehata** [comment]
@VePink setting the alpha works the same way regardless of what format the source image is in. Here's the [same example from before with a JPEG image](https://sandcastle.cesium.com/#c=hVRrb9owFP0rV3whSJnzAMrWUrSObSpSt1Vd99AUCbnJJXh17Mg2IFbx32cnpQkwac6X3Mc5vva512uqYM1wgwouQeAGpqjZqiDfK5/XTStzKoWhTKDq9i4SkYgguMoyYAXNEUpOBZJErC3TzHnmlWduUBvLWZMTFIYZhprQLPOeEgHPS9ACz6F7h1lN1PWbWCm1xUhxvi9qSpVlZVT0yULJ4j3mClF78ZCEUTgajXwYDskgevO6H/sQhyTstdkc/Tm09m55Wye/dR7wjrcckG+fZ/fznz4c8bqVsQKFtqXqA6oXcOz1YxL6EJ2dYgtqUDHKD5DVRX56jtwqWaIyW/COinerEsHeICFB9auDmmJ+I3M5n0ouFfld5l3/FJq6YHO5VeqP69n9B7JhZnnFyyX1QjLsHSJ3LXtX/+7qrqh74J2UjwVVj/PQqv+U2S5ggjoZ4X86QkNcSxqd9X0IApgJZhkotx3BhAEuRc7MKnNdtwc44eNwFIf/BFjjKL9vVQQrhTnNXiLLlwa8Xz3wil4LIxWzbXx0lmukGRP5LTPp8k5yfnCiBhsN6sqmtt8VtXtUqBb5q+ggoXR8rbAtNzGuXvc1acrt2GRlK0XriYlgd9FOXPDtS9QHT7tzuTn+aP1GvogGoRWxnlidop3rtIITjca9CF4jbu+i43fG2mw5TuoC3rKilMrASnHPdqPBwg6X1Tl4WKWPaEiqteuTcbAHjTO2BpZdJp2jVybpQMqp1jayWHH+lf3BpDMZBzb/AMZldYtf1qg43bqUZTS5qZ2EkHFgzVOUkZI/UNVi/As).

I don't think the FrustumGeometry supports applying a texture to it since it's mainly used to visualize the camera's field of view.

I'm going to close this issue since there isn't an actionable bug for us to resolve here, but feel free to follow up here or on [the Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev) if you have more questions!
