### ISSUE TITLE
Tiling issue with asset id: 61435

### ISSUE THREAD

**Issue by shgavman** [AnalyticalGraphicsInc/cesium-ion-community#261]
Hey there,

Cesium Ion seems unable to Tile my assets. It made progress (52% for asset ID 61435), stayed on 52% all night and eventually gave up with the message "We're having trouble with your data...". 

The file is 720 MB. It's an .fxb file created using capturing reality. 

I'm having a similar problem with Asset ID 61494 (stuck on 9% tiling). 

I'm able to open these model in a number of other softwares including blender and the windows 3D viewer so I don't think it's a problem with the models. 

Many thanks!

**Comment by OmarShehata** [comment]
Hey @shgavman  - it looks like you selected "3D Model" when tiling this model. Since this is a photogrammetry model, you should select "3D Capture" instead. That may be one cause of why it's failing.

Can you try re-uploading it with 3D Capture instead and let me know if that works? If not, please let me know the asset ID of that job as well and we can take a look.

Also as a tip to make upload faster, you can ZIP your files before uploading. Make sure you upload all related files (including any textures/image files) used by the model so it shows up correctly when tiled in Cesium ion.

**Comment by shgavman** [comment]
That worked a treat. Thank you very much. 

A background to my error for anyone that finds themselves in a similar position. I had tried uploading different versions with all the various setting options. The 3D Model option had partially worked but it said something like "tile location not set" at the bottom left of the model preview. In [this](https://groups.google.com/forum/#!topic/cesium-dev/uu3UaoYhv6Y) forum Omar resolved this problem for another user.

**Comment by OmarShehata** [comment]
Glad to hear that worked @shgavman ! Thanks for confirming.

Generally I would use "3D Capture" for any model that was captured from some real world data (typically photogrammetry) and "3D Model" for data that's authored in a modelling environment (typically BIM/CAD etc.).
