### ISSUE TITLE
Tiling issue with asset id: 62952

### ISSUE THREAD

**Issue by CHENJIAMIAN** [AnalyticalGraphicsInc/cesium-ion-community#263]
<Please provide a short summary of your data.>

**Comment by OmarShehata** [comment]
The problem with this dataset and https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/262 is that the relative URLs in the tileset are incorrect. Instead of:

```
          "url": ".Data/Tile_+000_+005/tileset.json"
```

it should be:

```
          "url": "./Data/Tile_+000_+005/tileset.json"
```

But it also looks like the b3dms are using an invalid extension (`KHR_technique_webgl` instead of `KHR_techniques_webgl`, see https://github.com/AnalyticalGraphicsInc/cesium/issues/6149#issuecomment-429003621). How was this tileset generated?

**Comment by OmarShehata** [comment]
I'm going to close this, but @CHENJIAMIAN feel free to follow up if you're still having issues.
