### ISSUE TITLE
Photogrammetry fails to tile

### ISSUE THREAD

**Issue by xiaomozi** [AnalyticalGraphicsInc/cesium-ion-community#264]
i want to convert obj file to 3dtileset . Asset ID 63876.

**Comment by OmarShehata** [comment]
Thanks for reporting this @xiaomozi . One thing I'd recommend here is to select "3D Capture" when tiling since this is a photogrammetry model. But there appears to be a bug with this specific model on our end.

Can you tell me how this model was generated? Have you run into issues with other models you've uploaded?

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
