### ISSUE TITLE
Issue tiling CityGML Berlin

### ISSUE THREAD

**Issue by janniklas-jakob** [AnalyticalGraphicsInc/cesium-ion-community#274]
Hey,

I'm having issues when uploading textured CityGML (heavily zip compressed). Asset ID 69937.
The file was downloaded from [here](https://www.businesslocationcenter.de/downloadportal/) The official open data website of Berlin, Germany.
I had no issues with the untextured and uncompressed .gml file (ID: 69986).
I hope somebody can help with this.

Best regards
Jahan

**Comment by OmarShehata** [comment]
Thanks for bringing this up @MrJahan. The issue here turned out to be that some images in this particular dataset failed to be decoded, which caused the job to fail. We're pushing out a fix to ignore these invalid images and continue. I'll update this issue when this fix is deployed early next week or later this week.

**Comment by OmarShehata** [comment]
Thanks again for reporting this @MrJahan . This issue has now been fixed. If you re-upload your CityGML it should now succesfully tile. You can see when the fix was deployed in the Cesium ion changelog: https://cesium.com/ion/changelog#2020-02-11
