### ISSUE TITLE
Add support for pre-tiled TMS/WMTS uploads

### ISSUE THREAD

**Issue by lazydino** [AnalyticalGraphicsInc/cesium-ion-community#276]
Asset ID 71997. I am uploading a zip file that contains the lunar textures arranged in TMS (at least I think so...), but ION dose not seem to  handle it? Could you help?

The zip file just contains directories and files under 'moon' directory as shown in the attachment. 

![image](https://user-images.githubusercontent.com/1158846/73886881-48c0c380-481f-11ea-9023-d883456ce79f.png)

I specify it as image raster when uploading the file. I am able to test these images on my VPS with a cesium web app by  creating a cesium imageryProvider:

```
            var imageTileURL = window.location.protocol + '//terrain.magnetar.net/tilesets/texture/moon';
            options.imageryProvider = Cesium.createTileMapServiceImageryProvider({
                url: imageTileURL,
                maximumLevel: 8,
                fileExtension: 'jpg'
            });
```

**Comment by OmarShehata** [comment]
The issue here is that Cesium ion doesn't support uploading pre-tiled imagery. For reference, here's the [full list of supported uploads](https://cesium.com/docs/tutorials/uploading/). 

We [recently added support for uploading pre-tiled 3D Tiles](https://cesium.com/ion/changelog#2019-10-03), so this could be another cool feature to see. If anyone else would like to see this supported, please :+1: or comment here!

In the meantime, @lazydino do you have the source GeoTIFF this was generated from? If so, you can upload that and have ion create the TMS tileset from it.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

This issue has been moved here: https://community.cesium.com/t/support-pre-tiled-wmts-tms-imagery-in-cesium-ion/10503
