### ISSUE TITLE
Tiling issue with asset id: 72232

### ISSUE THREAD

**Issue by susgut** [AnalyticalGraphicsInc/cesium-ion-community#277]
I have uploaded this asset (downloaded from https://demos.cesium.com/NewYork/?view=-74.01881302800248%2C40.69114333714821%2C753.2406554180401%2C21.27879878293835%2C-21.343905508724635%2C0.0716951918898415 ) to try to replicate the CesiumDemo called 3D Tiles Feature Picking available at https://demos.cesium.com/NewYork/?view=-74.01881302800248%2C40.69114333714821%2C753.2406554180401%2C21.27879878293835%2C-21.343905508724635%2C0.0716951918898415 , but it is not working (not in my code neither in the visualization area of "my assets").
What is happening? 
Many thanks, best,
   Susana

**Comment by OmarShehata** [comment]
@susgut the issue here is that the ZIP file contains a `.shp.xml` file, which is a shapefile, but gets interpreted as a CityGML file, and thus the job fails. This is recorded as a bug here: https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/199 so I'm going to close this.

For your case, you can fix this by removing the shp.xml before uploading. Let me know if you're still having issues!

**Comment by susgut** [comment]
I have reviewed the zip file and id does not contain any .shp.xml file, so I am afraid that this is not the problem. Thank you anyway.
