### ISSUE TITLE
Tiling issue with asset id: 72229

### ISSUE THREAD

**Issue by susgut** [AnalyticalGraphicsInc/cesium-ion-community#278]
I am having problems uploading this file (downloaded from https://demos.cesium.com/NewYork/?view=-74.01881302800248%2C40.69114333714821%2C753.2406554180401%2C21.27879878293835%2C-21.343905508724635%2C0.0716951918898415 ). I thought I have posted yesterday about this issue, but I have indicated the wrong assetID. In this case, the zip does not contains any .shp.xml file, so I do not know what could be the problem.
Many thanks.

**Comment by OmarShehata** [comment]
The issue here is that the files in that zip are gzipped. So if you open the tileset.json file in a text editor you'll notice you see binary data, not a JSON file.

We are working on making this NYC tileset part of the Cesium ion asset depot. In the mean time you'll either need to ungzip all the files, or upload the original CityGML with the shp.xml files removed.
