### ISSUE TITLE
Cesium visualization issue with asset id: 72617

### ISSUE THREAD

**Issue by zhangxrk** [AnalyticalGraphicsInc/cesium-ion-community#279]
<Please provide a short summary of your data.>
I made a model in 3dmax,it has skinning animation,why can't load it?

**Comment by OmarShehata** [comment]
The issue here is that this model does not contain a defined skeleton, which should be optional, but CesiumJS requires. See this issue for more details on this bug: https://github.com/AnalyticalGraphicsInc/cesium/issues/8175

In the meantime as a workaround you can export your model as a Collada model with animations then upload that to Cesium ion.
