### ISSUE TITLE
Polygon Geometry Render Error

### ISSUE THREAD

**Issue by hendrix-j** [AnalyticalGraphicsInc/cesium-ion-community#309]
I've found an oddly specific rendering issue when learning how to use geometries. I was attempting to create a sort of warped box. The first 5 sides came up and looked great, but the last side would only render a triangle and not a quadrilateral. If you manipulate any decimal value of `pt6` it will render properly.

Here's the code:

```javascript
let viewer = new Cesium.Viewer('cesiumContainer');

let pt1 = [-108.0, 25.0, 100000];
let pt2 = [-100.0, 25.0, 200000];
let pt3 = [-100.0, 30.0, 300000];
let pt4 = [-108.0, 30.0, 400000];
let pt5 = [-108.0, 25.0, 600000];
let pt6 = [-100.0, 25.0, 700000];
let pt7 = [-100.0, 30.0, 800000];
let pt8 = [-108.0, 30.0, 900000];
let side_positions = [
    //[...pt1, ...pt2, ...pt3, ...pt4], //bot
    //[...pt5, ...pt6, ...pt7, ...pt8], //top
    //[...pt1, ...pt2, ...pt6, ...pt5], //south
    //[...pt3, ...pt4, ...pt8, ...pt7], //north
    //[...pt1, ...pt5, ...pt8, ...pt4], //west
    [...pt2, ...pt3, ...pt7, ...pt6], //east
];

let instances = [];
for (let sidepos of side_positions){

    let side = new Cesium.PolygonGeometry({
        polygonHierarchy : {
            positions: Cesium.Cartesian3.fromDegreesArrayHeights(sidepos),
        },
        perPositionHeight : true,
    });

    let sideInstance = new Cesium.GeometryInstance({
      geometry : side,
      attributes : {
        color : new Cesium.ColorGeometryInstanceAttribute(1.0, 0, 0, 0.5)
      }
    });
    
    instances.push(sideInstance);
}

viewer.scene.primitives.add(
    new Cesium.Primitive({
      geometryInstances : instances,
      appearance : new Cesium.PerInstanceColorAppearance(),
    })
);
```

![image](https://user-images.githubusercontent.com/20349377/79532335-5faf3d80-803a-11ea-95ea-0e2331e6e598.png)

**Comment by OmarShehata** [comment]
I'm not sure why this is happening - my best guess is there may be an edge case in [PolygonGeometry.createGeometry](https://github.com/CesiumGS/cesium/blob/44acf6641b7cab4fe4a2624e12a3abc2c66b0777/Source/Core/PolygonGeometry.js#L1072) if a polygon is exactly aligned with the surface normal at a given position like that. I'd be curious if you see the same issue [using Coplanar polygons](https://sandcastle.cesium.com/index.html?src=development%2FCoplanar%20Polygon.html).

The Cesium community forum (https://community.cesium.com/) is a better place to ask this question since this repository is for [Cesium ion](https://cesium.com/ion/) related issues. I'd post your findings there if you make any more progress here!
