### ISSUE TITLE
Cesium Ion unavailable in Ukraine

### ISSUE THREAD

**Issue by akafrmn** [AnalyticalGraphicsInc/cesium-ion-community#31]
Hi,

Ive met an issue using cesium ion and access to cesium.com from Ukraine. Receiving 403 response from CloudFront.

Using cesium from 1.41.0 met a lot of 403 errors during exploitation. Can`t even loaf Terrain.

Is there any reason why access blocked form Ukraine? And how this can be mitigated ?

**Comment by mramato** [comment]
@akafrmn, thanks for reporting this issue, we understand your frustration.

We are a US-based company and our current understanding of US law is that we must prevent access from Crimea. While we would love to make ion available in the rest of Ukraine, our current hosting provider, AWS, does not distinguish between Ukraine and Crimea. As a Ukraine resident, if you have any thoughts on this issue, or would like to reach out to AWS directly to ask them to better support Ukraine, that would be a big help.

This issue is always evolving, so if and when we have a solution we will update this issue with the details. Our long term goal is definitely to allow access from Ukraine. 

In the meantime we do have on premises solutions available for our tilers and Cesium World Terrain if you are interested in bringing ion capabilities into your organization. Please contact Tim at tim@cesium.com for details.

**Comment by Dmitry404** [comment]
@mramato It was very disappointing to find that I, being in Ukraine, could only access cesium.com with a proxy. Meanwhile docker guys faced and solved! same issue https://github.com/docker/for-linux/issues/57#issuecomment-314505535 

Surely Cesium ion is not the only service hosted by AWS meaning there has to be a solution. This would make many other services to be unavailable from Ukraine which haven't reported yet.

**Comment by mramato** [comment]
@Dmitry404 thank you for the link, we'll certainly look into it.  It is our goal to unblock Ukraine as soon as we can while staying compliant with US law.

**Comment by chaficnajjar** [comment]
@mramato [cesium.com](https://cesium.com) is also not accessible from Lebanon. Could your company reconsider whether it's necessary to block certain countries? I don't know of any other US-based company that blocks access to their websites to users in Lebanon.

**Comment by hpinkos** [comment]
Also reported by @alexander-entin in https://github.com/AnalyticalGraphicsInc/cesium/issues/7679

**Comment by OmarShehata** [comment]
Also reported by @nbaghm in https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/200.

**Comment by mourner** [comment]
@mramato just chiming in here to say this is very disappointing and also seems quite absurd. I'm not aware of ANY other service provider, US or otherwise, that blocks the whole of Ukraine because of US sanctions against Crimea (even though the majority likely use AWS). Therefore I can only assume that this comes from a colossal misinterpretation of US law and how it applies to situations like this from your side. 

> It is our goal to unblock Ukraine as soon as we can while staying compliant with US law.

More than a year has passed without any movement on this. Note that Crimean peninsula currently has an estimated population of 2 million, while Ukraine excluding Crimea has **42 million**.

@bonnie-bogle any chance you could look into the matter? This is unacceptable and extremely concerning behavior from otherwise such a wonderful company.

**Comment by ghost** [comment]
@mourner and everyone here, thank you for bringing this up and we're not happy with this either. We very much want to make Cesium accessible again to users in Ukraine, understand that our current approach falls short for the vast majority of people in the country, and apologize for the delay in addressing this. We had some limitations previously that made this tricky that should no longer pose a problem. 

We're actively working on this and will have more information to share with you shortly. 

Thank you for your patience - more soon.

**Comment by mourner** [comment]
Just a gentle reminder that Cesium is still the only tech company I know that punishes a 42-million country for being the _victim_ of military aggression, while still happily open for business with the aggressor.

**Comment by nop1984** [comment]
@mourner not the only, if take in attention OFAC sanctions - for example Stipe or PayPay will never work in Ukraine untill russian invasions into Ukraine goes and untill Crime is annexed. Even after than our bank system has to develop garantee of cut off for tenth of our "businessman" who play with russia side and are in sanction list.

**Comment by mourner** [comment]
@nop1984 PayPal not supporting receiving funds in Ukraine has nothing to do with Crimea, it was like this before annexation, and the rest of the service successfully complied with sanctions by denying transactions for Crimea specifically. Meanwhile, companies like Transferwise operate in Ukraine without problem, and it'a only a matter of time for Stripe. But it's not relevant to this discussion anyway — let's not compare the banking sector regulations with a country-wide ban on using a mapping / data viz service.

**Comment by nop1984** [comment]
@mourner I am sure about state of things I wrote above. And I had mailing about it with Stripe and treasury.gov
TransferWise is not US company, but UK
Yes, PayPal was not working even before, but it doesn't change OFAC restrictions rules which appeared in 2014
Yes, its related to bank sector, but sanctions include providing any services to persons or companies in sanctions list. And if US based service provider not sure he can't filter out such persons he "bans" all heap not to have headache with government suddenly.

**Comment by mramato** [comment]
I’m very happy to announce that Cesium is now available in Ukraine! Can those of you in Ukraine please try it out and confirm it is working? Thank you!

We just just released new IP-level blocking capabilities which allow us to comply with US law regarding Crimea while allowing access from the rest of Ukraine. Thank you for your patience as we sorted this out and I’m sorry it took so long to make this happen.

**Comment by mourner** [comment]
Thanks a lot for addressing this! It works now — the issue can be closed.

**Comment by Dmitry404** [comment]
> Can those of you in Ukraine please try it out and confirm it is working?

It does. Thank you

**Comment by mramato** [comment]
Awesome.

**Comment by DaCuteRaccoon** [comment]
`:C` Sorry for you guys in Ukraine right now. I hope Ukraine wins the war
