### ISSUE TITLE
Error while reading large glTF

### ISSUE THREAD

**Issue by MadTrout** [AnalyticalGraphicsInc/cesium-ion-community#318]
Asset ID 102672.

**Comment by OmarShehata** [comment]
Thanks for reporting @MadTrout . This appears to be a bug with reading this large glTF file. Are you able to export this as one or more smaller pieces, perhaps less than 1 GB each? ion will automatically fuse them together.

I would also recommend choosing "3D Capture" or "3D Model" when uploading assets this large to tile it into 3D Tiles, since most clients will not be able to efficiently render untiled glTF models that are this large.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

If you have any follow up questions, please post on the community forum!
