### ISSUE TITLE
Mutable access tokens

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium-ion-community#32]
Currently tokens are immutable and can not be changed once created.  We've had several users request the ability to modify an access token after the fact.  One example is adding or removing assets from the token.

**Comment by OmarShehata** [comment]
I ran into this as well when putting together the [Vricon demo](https://cesium.com/blog/2019/06/04/vricon-partnership/). The annoyance was mostly that I needed the specific token used to have access to only a certain number of assets, but I forgot to add terrain, so I had to go back and manually re-add all my assets + terrain in a new token.

To be clear, I believe editing a token will essentially create a new one, so you'd need to update the token in your application (since the token itself communicates what it can access), but this is more of a UX convenience feature, to not have to manually redo everything when you're modifying a token.

**Comment by pding** [comment]
So is there a timetable when this feature will be release?

**Comment by OmarShehata** [comment]
@pding there isn't a specific timeline for this - we've been working on improving Cesium ion's robustness and handling more kinds of data, which you can follow in the change log here: https://cesium.com/ion/changelog

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
