### ISSUE TITLE
Tiling issue with asset id: 106259

### ISSUE THREAD

**Issue by ofirbentov** [AnalyticalGraphicsInc/cesium-ion-community#320]
Hi, 
Im uploading obj or coallada files made in agisoft, but it send this error at the end of uploading process to cesium. any thoughts?

**Comment by OmarShehata** [comment]
You've selected to host this model as a glTF. Since this is a very large model we recommend you tile it into 3D Tiles. You can do this by selecting the "3D Capture" option when uploading. Although I noticed this model does not have any associated textures. Is this intentional or is it meant to be textured?

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

If you have any follow up questions, please post on the community forum!
