### ISSUE TITLE
OSM buildings: Terrain inconsistencies

### ISSUE THREAD

**Issue by tkazik** [AnalyticalGraphicsInc/cesium-ion-community#321]
Dear Cesium Team

First of all, congrats and thank you for the OSM building update...awesome work @kring !
I did some preliminary tests and noticed a few things, see:

![cesium_OSMbuilding_analysis](https://user-images.githubusercontent.com/15689124/83488040-73104e00-a4ac-11ea-94b7-46e1bc6840a1.jpg)
LH: Cesium World Terrain; RH: Custom Flat Terrain (uploaded through ION)

Two things:
- CWT: Due to the "wobbliness" of the CWT, the terrain penetrates some buildings
- Custom Terrain: Some buildings seem to be missing (see red circle on RH image part)

For debugging purposes: The terrain id is 11575.

Thank you for your investigations!

**Comment by OmarShehata** [comment]
Thanks for the kind words @tkazik ! The reason the buildings disappear with your terrain is because the Cesium OSM Buildings are clamped to Cesium World Terrain, and so your terrain is slightly higher in that area, and so the building is underneath.

The reason you see that artifact on the left side is because while all the vertices of that building are above the terrain, that little hole is poking through the center. We could fix this by adding an extra check for these cases.

**Comment by OmarShehata** [comment]
This was fixed with the updated of Cesium OSM Buildings a few weeks ago! https://cesium.com/ion/changelog#2020-07-21
