### ISSUE TITLE
Tiling issue with asset id: 113464

### ISSUE THREAD

**Issue by FlorianFehring** [AnalyticalGraphicsInc/cesium-ion-community#331]
Hello,
Cesium Ion webpage reports an error with my uploaded data. Please have a look at whats gone wrong at assert id 113464.

Thanks,
Florian Fehring

**Comment by OmarShehata** [comment]
Thanks for reporting @FlorianFehring . This is a bug on our end. I'll update this issue once we have a fix or a workaround.

**Comment by thailekha** [comment]
Hi @OmarShehata, is there any update on this? I probably ran into the same issue as @FlorianFehring , Cesium Ion keeps returning 400 for the asset (asset id 114251)

![Screenshot from 2020-06-22 10-17-24](https://user-images.githubusercontent.com/10671610/85310711-960d9c80-b471-11ea-9651-0de7a12b18b4.png)
![Screenshot from 2020-06-22 10-19-20](https://user-images.githubusercontent.com/10671610/85310867-c7866800-b471-11ea-8479-1c7801982000.png)

I've generated a token for my account instead of using the default token, but I notice that the assets I uploaded to Ceisum prior to the change on 2020-06-12 render just fine
![Screenshot from 2020-06-22 10-22-44](https://user-images.githubusercontent.com/10671610/85311168-3f549280-b472-11ea-87ff-e225f7852ae0.png)

**Comment by OmarShehata** [comment]
Just to close the loop here, @thailekha that was a separate error that was resolved here https://github.com/CesiumGS/cesium-ion-community/issues/333.

@FlorianFehring we have a potential fix we're still testing. If you've run into any other point cloud assets that failed please include them here as well.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
