### ISSUE TITLE
Tiling issue with asset id: 117850

### ISSUE THREAD

**Issue by YRstronger** [AnalyticalGraphicsInc/cesium-ion-community#337]
I am trying to write my own 3D Model to GLTF file，including vertex , texture and image data. I am trying write as the example model but when i upload the file, ion show it cannot be opened.

**Comment by OmarShehata** [comment]
@YRstronger the glTF model you're uploading is not valid. You can confirm this by uploading it in other glTF viewers like: https://gltf-viewer.donmccurdy.com/.

Let me know if this helps. Feel free to follow up here or on the community forum: https://community.cesium.com/. I'm going to close this since we have another issue to improve the error detection and reporting here: https://github.com/CesiumGS/cesium-ion-community/issues/319
