### ISSUE TITLE
AssetsID: 125362 Error: File Not Found

### ISSUE THREAD

**Issue by lxydft** [AnalyticalGraphicsInc/cesium-ion-community#346]

**Comment by OmarShehata** [comment]
@lxydft you need to specify a full path to the `tileset.json` file when uploading pre-tiled 3D Tiles.

In this case, the correct path should be `zztest/tileset.json` since your JSON file is one directory down. Alternatively, you can re-zip your files such that the `tileset.json` is at the root directory of the ZIP.
