### ISSUE TITLE
Tiling issue with asset id: 126565

### ISSUE THREAD

**Issue by asik-babu** [AnalyticalGraphicsInc/cesium-ion-community#347]
i have converted .lwo into .dae and upload to cesium it gives me error.how can i create visualize the moon in cesium instead of the earth. please guide me.

**Comment by OmarShehata** [comment]
I noticed you used Assimp to convert this LWO to DAE. Have you tried outputting glTF directly? That's the format you ultimately need to visualize in Cesium so that'll be one less conversion required. The DAE file you uploaded may be invalid. 

> how can i create visualize the moon in cesium instead of the earth

You may find this forum discussion useful, there's a code example visualizing the lunar surface there instead of the Earth: https://community.cesium.com/t/how-to-tile-mars-themis-raster-for-cesium/10356/2?u=omar

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

If you have any follow up questions, please post on the community forum!
