### ISSUE TITLE
Processing CityGML where Textures are not in the BaseFolder

### ISSUE THREAD

**Issue by Tugark** [AnalyticalGraphicsInc/cesium-ion-community#36]
Our CityGML models are delivered with their textures lying in a subfolder, e.g.

```
└───Data
    │   citymodel.gml
    │
    └───images
         145876.jpg
         145877.jpg
         ....
```

As such, the CityGML also contains the `images/` path for the textures. While all files can be uploaded, including the directory, I believe that the directory structure is not mirrored on Cesium ION and as such, my model does not get texturized. When I move all images to the basefolder and edit the CityGML file by removing `images/`, it does work nicely.

I think that this behaviour is intended and understandable, though I think any hint on that matter when uploading would be helpful to avoid waiting for the processing of the file just to find that it did not work properly :-)

Best,
Lukas

**Comment by mramato** [comment]
Hi @Tugark, thanks for giving ion a try!  Are you selecting the files by clicking `Choose files` or are you dragging and dropping the folder into ion?

If you drag and drop the entire folder at once, the directory structure is maintained and your data should work as-is.

If you select the files through the user interface, then browser limitations remove the folder paths and the problem you are describing occurs. I think our best bet is to update our tilers to always look in the top-level folder if a texture is missing at the specified location so that if the structure isn't there we can still find it.  But this isn't a 100% fix either.  We can certainly leave this issue open until we have a mitigation strategy in place.

**Comment by Tugark** [comment]
Yeah, I guess that was the problem. Thanks for highlighting that difference :-)

I don't know if you're doing any beforehand validation - but I read from other issues that you also check for SRS availability in CityGML file. Couldn't you add another validation that scans for the textures and warns the user if all textures are "missing"? Coupled with the strategy you mentioned above, a warning would not have to be issued, but would be issued if the user e.g. forgot to upload the textures and you don't find any textures at all.

On a related note - could you also imagine allowing for zipped uploads? That way, the issue at hand would not be any problem, since you could unzip the files on your server to the same directory structure.

**Comment by hpinkos** [comment]
Hello @Tugark, supporting zip file uploads has been on our roadmap, but I also created this issue to track that feature: #37

**Comment by mramato** [comment]
ion now supports zip uploads. You can read all about it here: https://cesium.com/blog/2019/03/07/zip-uploads/
