### ISSUE TITLE
Improve support for GeoTIFF reprojections

### ISSUE THREAD

**Issue by fnicollet** [AnalyticalGraphicsInc/cesium-ion-community#4]
Hello,

I was trying to upload a terrain file  (TIFF format), but it failed (no specific error message). The file is in a french projection system, probably not supported by Cesium (EPSG:3946 http://epsg.io/3946). If you want to try it, the file can be downloaded here:
http://drive-in.synaaps.com/telechargementdirect.php?refespace=3851&arbo=UHVibGlj&file=188e418d14a487049c9e967d3f2f2c53&key=7092c7f0dcb304b2f36d79a281e1bec6

If I try the reprojected file, it (kind of) works, see the reprojected TIFF:
http://drive-in.synaaps.com/telechargementdirect.php?refespace=3851&arbo=UHVibGlj&file=e7c482631ed18e60c9994cbaa66010ce&key=41660fcc121e88cc783e3e62a2069d86

It would nice to have a more specific error message, explaining that this projection is not supported and that only projection XX and YY are supported (EPSG:3857 only I guess?)

Bonus point (might be worth opening another issue?), that Cesium ION would be able to reproject the TIFF data during the import

Thanks,
Fabien

**Comment by mramato** [comment]
Thanks @fnicollet, sorry for the slow reply. Most of the team was busy with FOSS4GNA last week.

We actually do reproject to `EPSG:3857` during the import process so I'll have to look into why this failed.  It's possible that `EPSG:3946` is not something we currently have reprojection information for.  We'll definitely want to fix this so your original upload attempt succeeds and we have a separate issue to improve the error message that is displayed when the problem is projection related.

Thanks again for reporting the issue.

**Comment by fnicollet** [comment]
Great! 3946 should work with gdal out of the box, unless you got the
gdal_data wrong or something, shouldn't be a big deal

Le lun. 21 mai 2018 18:32, Matthew Amato <notifications@github.com> a
écrit :

**Comment by OmarShehata** [comment]
This now prints the correct error, the original TIFF file does not have a coordinate system defined:

```
Error: Missing or invalid spatial reference system
File: MNT2012_Altitude_10m_CC46/MNT2012_Altitude_10m_CC46.tif
```
