### ISSUE TITLE
Upload GeoJSON?

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium-ion-community#55]
You can already upload KML, even though it isn't tiled, just to host it and serve it in your CesiumJS applications. It should be pretty easy to allow GeoJSON too right?

**Comment by mramato** [comment]
KML is not an officially supported feature, your account only has access to it because you are a beta user.  Uploading untiled KML will unlikely ever go into production (because we plan to tile it).

GeoJSON support will be added when ion supports vector tile generation.  It's unlikely that we'll add untiled geojson support.

**Comment by mramato** [comment]
We've created issue #130 as a general Vector tiling feature issue.  I'm going to close this and we can continue discussion there in the future.
