### ISSUE TITLE
Tiling issue with asset id: 10333

### ISSUE THREAD

**Issue by MustafaKya** [AnalyticalGraphicsInc/cesium-ion-community#57]
<Please provide a short summary of your data.>
![cesiumion](https://user-images.githubusercontent.com/33996460/48671171-7562bf80-eb35-11e8-9064-6ebc4b2d11f2.PNG)

**Comment by lilleyse** [comment]
Hi @MustafaKya 

It seems that the CityGML file isn't georeferenced and we weren't able to tile it. This is something we would like to support eventually but probably not in the short term.

In the meantime, since you are using FME as part of your workflow, are you able to georeference the data before passing it to the CesiumIonConnector?

**Comment by OmarShehata** [comment]
There's some discussion and proposed workarounds here: https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/35

I'm going to close this, but feel free to follow up there or open a new issue if it's still failing after georeferencing it.
