### ISSUE TITLE
Camera issue with the asset viewer when using ctrl+mouse and then using the mouse wheel

### ISSUE THREAD

**Issue by fnicollet** [AnalyticalGraphicsInc/cesium-ion-community#6]
Hello,

This issue is with the Asset viewer of Cesium ION, but more probably a Cesium issue itself.
On the TIFF file I uploaded, I get a Cesium view on the right, when I click the "house" button, it zooms on the extent:
![image](https://user-images.githubusercontent.com/1240481/40055929-fbf504ec-5849-11e8-8159-18f8c32ef45a.png)

If I use ctrl+mouse to get more "perspective", I get to this camera position for instance:
![image](https://user-images.githubusercontent.com/1240481/40055955-112d0cc4-584a-11e8-9c4a-c04b5d3b1db5.png)

If I use the mouse wheel once to zoom in, the camera seems to zoom in massively and I thing I get under the actual terrain:
![image](https://user-images.githubusercontent.com/1240481/40056001-3c18f60a-584a-11e8-948f-15e6f0f9808c.png)

I have to mouse wheel down about 10 times to get to the previous zoom.

The issue is reproduced on Chrome 66, on Windows 10, I can try in other browsers if needed

Fabien

**Comment by mramato** [comment]
I can reproduce this problem, thanks for reporting.  At face value it definitely sounds like a CesiumJS issue, but we will confirm that to be the case.  I'll link to the equivalent CesiumJS issue or PR once we have one and we'll keep this open until those changes make it into ion.

Thanks!

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

I believe this is a CesiumJS issue. We do have an issue open here for giving applications like Cesium ion more control over zoom speed: https://github.com/CesiumGS/cesium/issues/7978. Otherwise, we appreciate the feedback here and for any follow-up questions or comments, please use the community forum!
