### ISSUE TITLE
Tiling issue with asset id: 11150

### ISSUE THREAD

**Issue by Construkted-Reality** [AnalyticalGraphicsInc/cesium-ion-community#63]
The obj model was created in Reality Capture, and it was exported with 16 x 8k texture files.
The error message is quite vague. 
I can provide the source files if required.

**Comment by hpinkos** [comment]
Thanks for opening up an issue @outsider787.  We'll be able to look more into the issue next week

**Comment by Construkted-Reality** [comment]
Thanks.
It seems 10 texture 8k files give the same error.
However 4 x 8k texture files work just fine...

**Comment by Construkted-Reality** [comment]
An update from my end. 
I have uploaded the same model but created in Agisoft Photoscan with 12 x 8k textures, and Cesium Ion was able to tile it.

So it seems there's something weird with the files created by Reality Capture?

**Comment by mramato** [comment]
@outsider787 I've been looking into this and your model is definitely something we want to support (and I'm in the process of making fixes so that we can tile it).  That being said, your assumption is at least partially correct.  Reality Capture models seem to generate output that is very inefficient (in a spatial sense).  When there are multiple objs, instead of each obj having 1 texture atlas, it seems to reference little pieces of every texture.  That causes our tiler to load all of the textures for every model and introduced some memory pressure that we weren't handling very well.

The good news is that the improvements we're making will ultimately benefit all Reality Capture output.  I'll let you know when my changes go into production.

**Comment by mramato** [comment]
@outsider787 I'm happy to report that the update we released last night will now convert this model successfully.  Thanks again for the report.
