### ISSUE TITLE
Tiling issue with asset id: 11830

### ISSUE THREAD

**Issue by WilCodeBoer** [AnalyticalGraphicsInc/cesium-ion-community#67]
I'm trying to upload a 913.58mb GeoTiff which keeps failing to complete the tiling process. 
Getting no error besides the "Please create an issue" warning

**Comment by hpinkos** [comment]
Thanks for submitting this issue @WilCodeBoer!  Our tiling team will look into this shortly and get back to you once we have more information.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

This may have been fixed now. Since the asset has been deleted we can't re-test it. Give it a try, and if you have any follow up questions, please post on the community forum!
