### ISSUE TITLE
Tiling issue with asset id: 12087

### ISSUE THREAD

**Issue by SurajitChowbey** [AnalyticalGraphicsInc/cesium-ion-community#69]
Hi,
After uploading terrain data in cesium ION, I'm facing this issue.

> We're having trouble with your data. To help fix it, please open an issue in our Github repository.
> If you don't have a GitHub account, email Sean at sean.lilley@cesium.com with the asset ID: 12087.

**Data is in .tif format.**

**Comment by hpinkos** [comment]
Thanks for opening this issue @SurajitChowbey!  We will look into this shortly and let you know once we have more information.

**Comment by SurajitChowbey** [comment]
Hi,
Any updates?

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

This may have been fixed now. Since the asset has been deleted we can't re-test it. Give it a try, and if you have any follow up questions, please post on the community forum!
