### ISSUE TITLE
Add the ability to upload Shapefiles

### ISSUE THREAD

**Issue by fnicollet** [AnalyticalGraphicsInc/cesium-ion-community#7]
Hello,

Note sure if on the roadmap, but will Cesium be able to handle SHP upload (along with PRJ, DBF, etc.)?
I guess it would be very useful for the "Cesium ION Projects", so that you can create a Project where you overlay your vector data on your terrain data

Thanks,
Fabien

**Comment by hpinkos** [comment]
Yes, shapefiles are also on our radar.  We will likely have a shapefile to vector tiles converter on ion in the future.

**Comment by mramato** [comment]
Just to confirm @hpinkos' statement.  Yes, we absolutely want this.  However, we will most likely never have direct Shapefile support because it's not a very web-friendly format.  We absolutely plan to support uploading Shapefiles and converting them to 3D Tiles in a way that preserves all attributes/metadata and makes them streamable.  You will then be able to style them just like any other 3D Tiles tileset.  (Long term we will have built in styling to the project editor as well).

**Comment by fnicollet** [comment]
Thanks for both your answers,
Shapefile is not very web friendly but within a zip, it's quite easy to
detect. Also, you already allow for "side" files like tfw, so the shp side
file shouldn't be a problem?
If anything, it's very tool friendly, so it can be converted to geojson or
kml easily. KML seems to have issues at the moment, but i hope it will get
fixed to allow for a shp>kml>ion workflow at least

Fabien

Le lun. 21 mai 2018 18:45, Matthew Amato <notifications@github.com> a
écrit :

**Comment by kteneyck** [comment]
We're also looking forward to this feature. We have a lot of shapefile data and the process we go through hasn't been easy to convert our shapefiles into 3D Tiles.

**Comment by mramato** [comment]
We've created issue #130 as a general Vector tiling feature issue.  I'm going to close this but we'll comment here once vector tiling is available on ion.  Feel free to chime in on #130 if you have any thoughts.
