### ISSUE TITLE
Uploading a 26Mb KML in Cesium ION doesn't work

### ISSUE THREAD

**Issue by fnicollet** [AnalyticalGraphicsInc/cesium-ion-community#8]
Hello,

I tried uploading the following KMZ to Cesium ION:
http://drive-in.synaaps.com/telechargementdirect.php?refespace=3851&arbo=UHVibGlj&file=82dc2a97d85543c8946d1f6f5c552533&key=380efa41600d66ade496397a02336dbd
The KMZ is only 800Kb but unzipped, the KML inside is about 26Mb. Processing takes a long time, then nothing it shown, it freezes the browser during the preview. The project based on this asset seem to detect its extent (in south africa) but does not display it. The files has about 17600 polygons

Fabien

**Comment by mramato** [comment]
I apologize no one ever replied to this.  Direct KML/KMZ upload is/was a beta feature of ion that has never gone to production.  KML uploaded in this way does not go through the 3D tiling process and Cesium has issues loading KML of that size (mainly because KML is not a browser-friendly format).

We will eventually support tiling of KML 3D polygons into 3D Tiles, which will load and stream efficiently, but currently we only support uploading of KML City models with DAE files.  I wrote up #130 for this purpose. I'm going to close this, but feel free to keep an eye on #130 (and we'll remember to add a comment to this issue once that is implemented).
